from enum import Enum


class EmailTemplateEnum(Enum):
    ACCOUNT_CREATION_SUCCESS = "ACCOUNT_CREATION_SUCCESS"
    ACCOUNT_CREATION_FAILURE = "ACCOUNT_CREATION_FAILURE"
    MODIFY_ACCOUNT_SUCCESS = "MODIFY_ACCOUNT_SUCCESS"
    DEPOSIT_DOCUMENT_SUCCESS = "DEPOSIT_DOCUMENT_SUCCESS"
    DEPOSIT_DOCUMENT_ERROR = "DEPOSIT_DOCUMENT_ERROR"
    RESET_PASSWORD = "RESET_PASSWORD"

