# Generated by Django 4.1.9 on 2023-09-23 22:35

from django.db import migrations, models


def migrate_email_default_value_as_username(apps, schema_editor):
    CustomUser = apps.get_model('paperless', 'CustomUser')

    for mm in CustomUser.objects.all():
        mm.email = mm.username + "@file.com"
        mm.save()


class Migration(migrations.Migration):
    dependencies = [
        ('paperless', '0001_initial')
        ]

    operations = [
        migrations.RunPython(migrate_email_default_value_as_username),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
            )
        ]
