# Generated by Django 4.1.13 on 2023-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0003_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='prestation',
            field=models.CharField(blank=True, max_length=150, verbose_name='prestation'),
        ),
    ]
