# Generated by Django 4.1.13 on 2024-01-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0004_alter_customuser_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='technical_client_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='technical_client_id'),
        ),
    ]
