# Generated by Django 4.1.13 on 2024-01-23 14:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0005_customuser_technical_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, null=True, region=None, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='matricule'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='technical_client_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='technical_client_id'),
        ),
    ]
