# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.
# version: postgres without tikka

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  front:
    image: template_angular
    build:
      context: ..
      dockerfile: Dockerfile.front
    restart: unless-stopped
    ports:
    - "4200:4200"
    volumes:
      - ../src-ui:/src-ui
      - /src-ui/node_modules
    command: "ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check"


  webserver:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        QPDF_VERSION: 11.3.0
        PIKEPDF_VERSION: 7.2.0
        PSYCOPG2_VERSION: 2.9.6
        JBIG2ENC_VERSION: 0.29
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    # dev local : networks and external_links
    networks:
      - default
      - kafka_default
    external_links:
      - container_kafka:container_kafka
    # healthcheck:
    #   test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      # Add my volumes
      - /usr/src/paperless/src/documents/static/frontend/
      - ../src:/usr/src/paperless/src/
    env_file: docker-compose-dev.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
  redisdata:
# dev local :
networks:
 default:
   driver: bridge
 kafka_default:
   external: true
