# Generated by Django 1.10.5 on 2017-07-15 17:12

from django.db import migrations

from django.contrib.auth import get_user_model
import logging

User = get_user_model()
logger = logging.getLogger('documents')

def forwards_func(apps, schema_editor):
    # User.objects.create(username="consumer")
    logger.debug("Skip old migration")


def reverse_func(apps, schema_editor):
    logger.debug("Skip old migration")
    # User.objects.get(username="consumer").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_auto_20170715_1712"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
