# Generated by Django 4.1.13 on 2023-12-08 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1036_alter_savedviewfilterrule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestation', models.CharField(help_text='Name of the prestation', max_length=50, verbose_name='Prestation')),
                ('batch', models.CharField(help_text='Id of the actual batch', max_length=25, verbose_name='Batch')),
                ('document_index', models.CharField(help_text='Index of document in associated batch', max_length=4, verbose_name='Document index')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created')),
            ],
            options={
                'verbose_name': 'correlation id',
                'verbose_name_plural': 'correlation ids',
                'ordering': ('created',),
            },
        ),
    ]
