# Generated by Django 4.1.13 on 2023-12-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1037_correlationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='correlation_id',
            field=models.CharField(blank=True, default=None, help_text=('The associated correlation id of the file.',), max_length=50, null=True, unique=True, verbose_name='correlation id'),
        ),
    ]
