# Generated by Django 4.1.13 on 2023-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1038_document_correlation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlesstask',
            name='user_id',
            field=models.CharField(blank=True, help_text='User ID for the Task that was run', max_length=255, null=True, verbose_name='User ID'),
        ),
    ]
